name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main # or 'master' or any branch you want

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple_ci_cd_pipeline:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple_ci_cd_pipeline:latest
